# ============================
# Cloud Build for dbt prod
# Project: tw-rd-data-angus-tu
# ============================

steps:
  - name: 'python:3.10'
    id: 'Install dbt'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install dbt-bigquery

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Authenticate GCP'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $DBT_PROD_KEY_JSON > /tmp/prod-key.json
        export DBT_KEYFILE=/tmp/prod-key.json
        gcloud auth activate-service-account --key-file=$DBT_KEYFILE

  - name: 'python:3.10'
    id: 'dbt debug'
    entrypoint: 'bash'
    args:
      - '-c'
      - dbt debug --target prod

  - name: 'python:3.10'
    id: 'dbt build'
    entrypoint: 'bash'
    args:
      - '-c'
      - dbt build --target prod

secrets:
  - secretEnv:
      DBT_PROD_KEY_JSON: projects/tw-rd-data-angus-tu/secrets/DBT_PROD_KEY/versions/1
