steps:
  - name: 'python:3.11-slim'
    entrypoint: bash
    secretEnv: ['_DBT_KEYFILE']
    args:
      - '-c'
      - |
        pip install --quiet dbt-bigquery

        # 將 Secret 寫成檔案
        echo "$_DBT_KEYFILE" | tr -d '\r' > /workspace/keyfile.json
        export DBT_KEYFILE=/workspace/keyfile.json


        # 執行 dbt
        dbt deps --project-dir=demo_dbt --profiles-dir=demo_dbt
        dbt run --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod
        dbt test --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/tw-rd-data-angus-tu/secrets/DBT_PROD_KEY/versions/latest
      env: _DBT_KEYFILE
