steps:
  - name: 'python:3.11-slim'
    entrypoint: bash
    secretEnv: ['DBT_KEYFILE']
    args:
      - '-c'
      - |
        pip install dbt-bigquery
        echo "$DBT_KEYFILE" | tr -d '\r' > /workspace/keyfile.json
        export DBT_KEYFILE=/workspace/keyfile.json
        cat $DBT_KEYFILE
        dbt deps --project-dir=demo_dbt --profiles-dir=demo_dbt
        dbt run --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod
        dbt test --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/tw-rd-data-angus-tu/secrets/DBT_PROD_KEY/versions/latest
      env: DBT_KEYFILE
