steps:
  - name: python:3.10
    id: Install dbt
    entrypoint: bash
    args:
      - -c
      - |
        pip install --upgrade pip
        pip install dbt-bigquery

  - name: gcr.io/cloud-builders/gcloud
    id: Authenticate GCP
    entrypoint: bash
    args:
      - -c
      - |
        gcloud secrets versions access 1 --secret="DBT_PROD_KEY" > /tmp/prod-key.json
        export DBT_KEYFILE=/tmp/prod-key.json
        gcloud auth activate-service-account --key-file="$DBT_KEYFILE"

  - name: python:3.10
    id: dbt debug
    entrypoint: bash
    args:
      - -c
      - dbt debug --target prod

  - name: python:3.10
    id: dbt build
    entrypoint: bash
    args:
      - -c
      - dbt build --target prod
