steps:
  - name: 'gcr.io/cloud-builders/python:3.10'
    entrypoint: bash
    secretEnv: ['DBT_KEYFILE']
    args:
      - '-c'
      - |
        pip install dbt-bigquery
        dbt deps --project-dir=demo_dbt --profiles-dir=demo_dbt
        dbt run --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod
        dbt test --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/tw-rd-data-angus-tu/secrets/DBT_PROD_KEY/versions/latest
      env: DBT_KEYFILE
