steps:
  - name: 'python:3.11'
    entrypoint: bash
    secretEnv: ['_DBT_KEY']
    args:
      - -c
      - |
        pip install --quiet dbt-bigquery
        echo "$_DBT_KEY" > /workspace/keyfile.json
        export DBT_KEYFILE=/workspace/keyfile.json
        dbt run --project-dir=demo_dbt --profiles-dir=demo_dbt --target prod

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/tw-rd-data-angus-tu/secrets/DBT_PROD_KEY/versions/latest
      env: _DBT_KEY
