demo_dbt:
  outputs:
    dev:
      dataset: dbt_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: asia-east1
      method: oauth
      priority: interactive
      project: tw-rd-data-angus-tu
      threads: 1
      type: bigquery
    prod:
      dataset: dbt_prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /workspace/dbt_key.json
      location: asia-east1
      method: service-account
      priority: interactive
      project: tw-rd-data-angus-tu
      threads: 1
      type: bigquery
  target: dev